// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikhhvejlbpqdroftkuix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlraGh2ZWpsYnBxZHJvZnRrdWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTg1ODIsImV4cCI6MjA2ODQzNDU4Mn0.a3yeWAWgHv0Bl948yb7oOIHbWVMj3j_Vor4KVJiWhfU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});